<?php

/**
 * @file
 * Contains alterations for config.
 */

declare(strict_types=1);

use Drupal\config_rewrite\ConfigRewriterInterface;

/**
 * Implements hook_rewrite_config_update().
 */
function helfi_kasko_config_rewrite_config_update(string $module, ConfigRewriterInterface $configRewriter): void {
  $modules = [
    'helfi_tpr_config',
    'helfi_node_landing_page',
    'helfi_node_news_item',
  ];

  if (in_array($module, $modules)) {
    // Rewrite module configuration.
    $configRewriter->rewriteModuleConfig('helfi_kasko_config');
  }
}
